# filename: serverless.yml
service: nodejsawslambda

# The `provider` block defines where your service will be deployed
custom:
  bucket: "nodejsawslambdaartifact"
provider:
  name: aws
  stage: ${opt:stage}
  runtime: nodejs12.x
  region: us-west-2
  stackName: ${opt:stackName}
  deploymentBucket: ${opt:bucketName}
  deploymentPrefix: "ashish"
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        - "arn:aws:s3:::${opt:bucketName}/*"

# The `functions` block defines what code to deploy
functions:
  helloWorld:
    handler: handler.helloWorld
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: hello-world
          method: get
          cors: true