# filename: serverless.yml
service: nodejsawslambda

# The `provider` block defines where your service will be deployed
custom:
  bucket: "nodejsawslambdaartifact"
provider:
  name: aws
  stage: UAT
  runtime: nodejs12.x
  region: us-west-2
  stackName: testhelloworld
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        - "arn:aws:s3:::${self:custom.bucket}/*"
  s3:
    bucket:
      name: ${self:custom.bucket}
      existing: true
      # Eventual additional properties in camel case

# The `functions` block defines what code to deploy
# The `functions` block defines what code to deploy
functions:
  helloWorld:
    handler: handler.helloWorld
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: hello-world
          method: get
          cors: true
resources:
  Resources:
    StorageBucket:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: ${self:custom.bucket}
